### ISSUE TITLE
Responder preguntas

### ISSUE THREAD

**Issue by EuniceCano** [categulario/scheman#2]
Que responda las siguientes preguntas
- [X] interfaz para ver horarios de cada salón
- [x] interfaz para ver calendario de una materia
- [x] interfaz para ver calendario de un profesor

**Comment by categulario** [comment]
quizá pueda responder algunas de estas con la omnibarra automágica que diseñé

![whatsapp image 2017-01-27 at 3 24 37 pm](https://cloud.githubusercontent.com/assets/790756/22389050/533041b0-e4a9-11e6-8baf-4b1c11cf44fd.jpeg)
![whatsapp image 2017-01-27 at 3 27 16 pm](https://cloud.githubusercontent.com/assets/790756/22389051/55b31ae8-e4a9-11e6-8e90-5d84778ede10.jpeg)
![whatsapp image 2017-01-27 at 3 33 03 pm](https://cloud.githubusercontent.com/assets/790756/22389053/57a0e1c8-e4a9-11e6-8435-1aa14aa6ccee.jpeg)
